package l01.p15641;

// 주소: https://www.acmicpc.net/problem/15641
// 제목: SUPER SUPER BINARY SEARCH DELUXE 2.5: THE LEGEND OF THE GOLDEN
// MAZASSUMNIDA, EPISODE 2: THE MAZWAETL UNIVERSE, PART 2: THE PARALLEL UNIVERSE
// AND THE LOST MAZASSUMNIDA: GAME OF THE YEAR EDITION
// 결과: 맞았습니다!!
// 메모리: 4528 KB
// 시간: 0 ms

// 언어: Text
// 23
